apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-lgmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-lgmt
    app.kubernetes.io/part-of: test-annotations-app-oory
  name: test-annotations-lgmt
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-annotations-lgmt
status:
  loadBalancer: {}
